/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: Camera.bmp
* Dimensions:  43 * 62
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acCamera[] = {
  ________, ________, XXXXX___, ________, _XXXXX__, ________,
  ________, ______XX, XXXXXXX_, _______X, XXXXXXXX, ________,
  ________, _____XXX, XXXXXXXX, ______XX, XXXXXXXX, X_______,
  ________, ____XXXX, XXXXXXXX, X____XXX, XXXXXXXX, XX______,
  ________, ____XXXX, XXXXXXXX, X____XXX, XXXXXXXX, XX______,
  ________, ___XXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXX_____,
  ________, ___XXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXX_____,
  ________, ___XXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXX_____,
  ________, ___XXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXX_____,
  ________, ___XXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXX_____,
  ________, ____XXXX, XXXXXXXX, X____XXX, XXXXXXXX, XX______,
  ________, ____XXXX, XXXXXXXX, X____XXX, XXXXXXXX, XX______,
  ________, _____XXX, XXXXXXXX, ______XX, XXXXXXXX, X_______,
  ________, ______XX, XXXXXXX_, _______X, XXXXXXXX, ________,
  ________, ________, XXXXX___, ________, _XXXXX__, ________,
  ________, ________, ________, ________, ________, ________,
  XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXX_____,
  XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX____X, XXX_____,
  XXXX_XX_, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XX______,
  XXXX_XX_, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, X_______,
  XXXX_XX_, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, ________,
  XXXX_XX_, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX_XXXX, ________,
  XXXX_XX_, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX__XXX, ________,
  XXXX_XX_, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, ________,
  XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX____X, ________,
  XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ___XXXXX, XXX_____, ________, ________,
  ________, ________, ___XXXXX, XXX_____, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ____XXXX, XX______, ________, ________,
  ________, ________, ____XXXX, XX______, ________, ________,
  ________, ________, ____XXXX, XX______, ________, ________,
  ________, ________, ____XXXX, XX______, ________, ________,
  ________, ________, ___XX_XX, _XX_____, ________, ________,
  ________, ________, ___X__XX, __X_____, ________, ________,
  ________, ________, __XX__XX, __XX____, ________, ________,
  ________, ________, __X___XX, ___X____, ________, ________,
  ________, ________, _XX___XX, ___XX___, ________, ________,
  ________, ________, _X____XX, ____X___, ________, ________,
  ________, ________, _X____XX, ____X___, ________, ________,
  ________, ________, XX____XX, ____XX__, ________, ________,
  ________, ________, X_____XX, _____X__, ________, ________,
  ________, _______X, X_____XX, _____XX_, ________, ________,
  ________, _______X, ______XX, ______X_, ________, ________,
  ________, ______XX, ______XX, ______XX, ________, ________,
  ________, ______X_, ______XX, _______X, ________, ________,
  ________, _____XX_, ______XX, _______X, X_______, ________,
  ________, _____X__, ______XX, ________, X_______, ________,
  ________, _____X__, ______XX, ________, XX______, ________,
  ________, ____XX__, ______XX, ________, _X______, ________,
  ________, ____X___, ______XX, ________, _XX_____, ________,
  ________, ___XX___, ______XX, ________, __X_____, ________,
  ________, ___X____, ______XX, ________, __XX____, ________,
  ________, ___X____, ______XX, ________, ___X____, ________,
  ________, __XX____, _____XXX, X_______, ___XX___, ________

};

GUI_Bitmap_t bmCamera = {
  43, /* XSize */
  62, /* YSize */
  6, /* BytesPerLine */
  1, /* BitsPerPixel */
  acCamera,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */

