/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: SPLogo.bmp
* Dimensions:  128 * 64
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acSPLogo[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ___XXXXX, XXXXXXX_, ________, ________, ________, ________, ________, ________, _______X, XXX_____, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, ________, ________, ________, ________, ________, ________,
  __XXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, ________, ________, ________, ________, ________, ________,
  __XXXX__, ____XXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, _______X, XXX_____, ________, ________, ________, ________,
  __XXXX__, ____XXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, _______X, XXX_____, ________, ________, ________, ________,
  __XXXX__, ____XXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, _______X, XXX_____, ________, ________, ________, ________,
  __XXXX__, ____XXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, _______X, XXX_____, ________, ________, ________, ________,
  __XXXX__, ____XXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, _______X, XXX_____, ________, ________, ________, ________,
  __XXXX__, ____XXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, ________, ________, ________, ________, ________, ________,
  __XXXXX_, ____XXXX, ________, ________, ________, ________, ________, ________, _______X, XXX_____, ________, ________, ________, ________, ________, ________,
  __XXXXXX, ________, ________, ________, ________, ________, ________, ________, _______X, XXX_____, ________, ________, ________, ________, ________, ________,
  ___XXXXX, X_______, _____XXX, X___XXXX, X_______, XXXXXXXX, XXX_____, XXXX__XX, XXXX___X, XXX_____, XXXX___X, XXX____X, XXX___XX, XXX_____, ___XXXXX, X_XXXX__,
  ____XXXX, XX______, _____XXX, XXXXXXXX, XX_____X, XXXXXXXX, XXXX____, XXXXXXXX, XXXXX__X, XXX____X, XXXX___X, XXX____X, XXXXXXXX, XXXX____, __XXXXXX, XXXXXX__,
  _____XXX, XXX_____, _____XXX, XXXXXXXX, XX_____X, XXXXXXXX, XXXX____, XXXXXXXX, XXXXX__X, XXX___XX, XXX____X, XXX____X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__,
  ______XX, XXXX____, _____XXX, XXXXX_XX, XX_____X, XXX_____, XXXX____, XXXXXXX_, _XXXX__X, XXX__XXX, XX_____X, XXX____X, XXXXXXX_, XXXX____, _XXXXX__, XXXXXX__,
  _______X, XXXXX___, _____XXX, X_____XX, XX_____X, XXX_____, XXXX____, XXXX____, _XXXX__X, XXX__XXX, X______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  ________, XXXXXX__, _____XXX, X_____XX, XX______, ________, XXXX____, XXXX____, _XXXX__X, XXX_XXXX, _______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  ________, _XXXXXX_, _____XXX, X_____XX, XX______, ________, XXXX____, XXXX____, _XXXX__X, XXXXXXX_, _______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  ________, __XXXXXX, _____XXX, X_____XX, XX______, XXXXXXXX, XXXX____, XXXX____, _______X, XXXXXXX_, _______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  ________, ___XXXXX, _____XXX, X_____XX, XX_____X, XXXXXXXX, XXXX____, XXXX____, _______X, XXXXXX__, _______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  __XXXX__, ____XXXX, _____XXX, X_____XX, XX_____X, XXXXXXXX, XXXX____, XXXX____, _______X, XXXXXX__, _______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  __XXXX__, ____XXXX, _____XXX, X_____XX, XX_____X, XXX_____, XXXX____, XXXX____, _______X, XXXXXX__, _______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  __XXXX__, ____XXXX, _____XXX, X_____XX, XX_____X, XXX_____, XXXX____, XXXX____, _______X, XXXXXXX_, _______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  __XXXX__, ____XXXX, _____XXX, X_____XX, XX_____X, XXX_____, XXXX____, XXXX____, _______X, XXX_XXXX, _______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  __XXXX__, ____XXXX, _____XXX, X_____XX, XX_____X, XXX_____, XXXX____, XXXX____, _______X, XXX_XXXX, X______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  __XXXX__, ____XXXX, _____XXX, X_____XX, XX_____X, XXX_____, XXXX____, XXXX____, _______X, XXX__XXX, X______X, XXX____X, XXX_____, XXXX____, _XXXX___, __XXXX__,
  __XXXX__, ____XXXX, _____XXX, X____XXX, XX_____X, XXX__XXX, XXXX____, XXXX____, _______X, XXX___XX, XX_____X, XXX____X, XXX_____, XXXX____, _XXXXX__, __XXXX__,
  __XXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, XX_____X, XXXXXXXX, XXXX____, XXXX____, _______X, XXX___XX, XXX____X, XXX____X, XXX_____, XXXX____, _XXXXXXX, XXXXXX__,
  __XXXXXX, XXXXXXXX, _____XXX, XXXXXXXX, X______X, XXXXXXXX, XXXX____, XXXX____, _______X, XXX____X, XXXX___X, XXX____X, XXX_____, XXXX____, __XXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXX_, _____XXX, XXXXXXX_, ________, XXXXXX__, XXXX____, XXXX____, _______X, XXX_____, XXXX___X, XXX____X, XXX_____, XXXX____, ___XXXXX, XXXXXX__,
  ________, ________, _____XXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXX__,
  ________, ________, _____XXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXX__,
  ________, ________, _____XXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, _XXXX___, __XXXX__,
  ________, ________, _____XXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, _XXXX___, __XXXX__,
  ________, ________, _____XXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, _XXXX___, __XXXX__,
  ________, ________, _____XXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXX__,
  ________, ________, _____XXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXX__,
  ________, ________, _____XXX, X_______, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXX___,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX

};

GUI_Bitmap_t bmSPLogo = {
  128, /* XSize */
  64, /* YSize */
  16, /* BytesPerLine */
  1, /* BitsPerPixel */
  acSPLogo,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */

